include: package:netglade_analysis/lints.yaml

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
