// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNOzabjU57WHi4kK5tNF1aBu1ocXteVM',
    appId: '1:521897010746:web:0e4e2f0bb890407049f703',
    messagingSenderId: '521897010746',
    projectId: 'chronoflow-1',
    authDomain: 'chronoflow-1.firebaseapp.com',
    storageBucket: 'chronoflow-1.firebasestorage.app',
    measurementId: 'G-RCMC0XBGZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFvzzVJiIoJunMPan_DzguVtHqGiNess',
    appId: '1:521897010746:android:b8ac3be66d31cc1d49f703',
    messagingSenderId: '521897010746',
    projectId: 'chronoflow-1',
    storageBucket: 'chronoflow-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXxrUwvAQKb7uLRNKhnWlKzvJltvmq5Ps',
    appId: '1:521897010746:ios:b9caf5f1402d82d749f703',
    messagingSenderId: '521897010746',
    projectId: 'chronoflow-1',
    storageBucket: 'chronoflow-1.firebasestorage.app',
    androidClientId: '521897010746-3kpk4c5qc16n0msn1tde8fcke56j3amj.apps.googleusercontent.com',
    iosClientId: '521897010746-21a2ogrfr4ub71am6lvob795ip2v0tj8.apps.googleusercontent.com',
    iosBundleId: 'edu.nus.u.chronoflow',
  );
}
