default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_KEY_PATH"]
    )




    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "edu.nus.u.chronoflow",
      initial_build_number: 0
    )

    new_build_number = latest_build + 1
    UI.important "Latest TestFlight build: #{latest_build}"
    UI.important "New build number: #{new_build_number}"

    increment_build_number(
      build_number: new_build_number,
      xcodeproj: "Runner.xcodeproj"
    )



    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "edu.nus.u.chronoflow" => "match AppStore edu.nus.u.chronoflow"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      changelog: "Build #{new_build_number} - #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}",
      distribute_external: false,
      notify_external_testers: false
    )
  end
  lane :run_match do
    match(
      type: "appstore",
      readonly: true,
      keychain_name: "build.keychain-db",
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )
  end
end