default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :test do
    sh("pwd")
    sh("cd ../")
    project_root = File.expand_path("../..", Dir.pwd)
    sh("echo 'Project root: #{project_root}'")
    sh("pwd")
  end
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_KEY_PATH"]
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "edu.nus.u.chronoflow",
      initial_build_number: 0
    )

    new_build_number = latest_build + 1
    UI.important "Latest TestFlight build: #{latest_build}"
    UI.important "New build number: #{new_build_number}"

    increment_build_number(
      build_number: new_build_number,
      xcodeproj: "Runner.xcodeproj"
    )
    project_root = File.expand_path("../..", Dir.pwd)
    debug_info_path = "#{project_root}/debug-symbols/#{new_build_number}"
    sh(
      "flutter build ios --release --obfuscate --split-debug-info=#{debug_info_path} --no-codesign",
      log: true
    )
    archive_path = "#{project_root}/build/ios/archive/Runner.xcarchive"

    sh(
      "cd #{project_root} && xcodebuild archive " \
      "-workspace ios/Runner.xcworkspace " \
      "-scheme Runner " \
      "-configuration Release " \
      "-archivePath #{archive_path} " \
      "CODE_SIGNING_ALLOWED=NO " \
      "SKIP_FLUTTER_BUILD=true",
      log: true
    )

    build_app(
      skip_build_archive: true,
      archive_path: archive_path, # Using the exact same absolute variable
      export_method: "app-store",
      export_team_id: "2U93L9FLAY",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "edu.nus.u.chronoflow" => "match AppStore edu.nus.u.chronoflow"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      changelog: "Build #{new_build_number} - #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}",
      distribute_external: false,
      notify_external_testers: false
    )

    sh("gsutil cp #{debug_info_path}/app.ios-arm64.symbols gs://#{ENV["BUCKET_NAME"]}/iOS/#{new_build_number}/")

    
  end
  lane :run_match do
    match(
      type: "appstore",
      readonly: true,
      keychain_name: "build.keychain-db",
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )
  end
end